version: '3.7'

services:
  api:
    image: node:14
    command: bash -c "yarn && yarn dev && ls -la"
    restart: always
    ports:
      - ${PORT}:${PORT}
    working_dir: /srv/backend/app/
    volumes:
      - .:/srv/backend/app
    tmpfs:
      - /usr/local/share/.cache/yarn
    depends_on:
      - database

  database:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hello1
    ports:
      - 3306:3306
    volumes:
      - db_vol:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: database

volumes:
  db_vol:
    driver: local
